apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.shorthost }}-grav-service"
spec:
  selector:
    name: "{{ .Values.shorthost }}-grav-app"
  ports: 
  - name: grav-web
    protocol: TCP
    port: 80
    targetPort: 80
